-- This is an empty migration.

INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0001', 'ID', '工单唯一标识符', 'id', NULL, false, false, true, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0002', 'Title', '工单标题', 'text', '{"maxLength": 200}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0006', 'Description', NULL, 'rich_text', NULL, false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0009', 'Diagnosis', '工单诊断', 'select', '{"options": [{"id": "fan", "name": "Fan", "color": "#0052cc"}, {"id": "hashboard", "name": "Hashboard", "color": "#6554c0"}, {"id": "control_board", "name": "Control board", "color": "#00b8d9"}, {"id": "psu", "name": "PSU", "color": "#ff8b00"}, {"id": "temperature_sensor", "name": "Temperature sensor", "color": "#36b37e"}, {"id": "firmware", "name": "Firmware", "color": "#00875a"}, {"id": "overheating", "name": "Overheating", "color": "#ff5630"}, {"id": "other", "name": "Other", "color": "#e5e5e5"}]}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0007', 'Priority', '工单优先级', 'select', '{"options": [{"id": "low", "name": "Low", "color": "#36b37e"}, {"id": "medium", "name": "Medium", "color": "#fbca04"}, {"id": "high", "name": "High", "color": "#ff5630"}, {"id": "urgent", "name": "Urgent", "color": "#bf2600"}]}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0008', 'Category', '工单类别', 'select', '{"options": [{"id": "hardware", "name": "Hardware", "color": "#0052cc"}, {"id": "software", "name": "Software", "color": "#6554c0"}, {"id": "network", "name": "Network", "color": "#00b8d9"}, {"id": "power_supply", "name": "Power Supply", "color": "#ff8b00"}, {"id": "operational", "name": "Operational", "color": "#36b37e"}, {"id": "environmental", "name": "Environmental", "color": "#00875a"}, {"id": "other", "name": "Other", "color": "#e5e5e5"}]}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0011', 'Miners', NULL, 'miners', NULL, false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0004', 'Created At', NULL, 'datetime', NULL, false, false, true, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0005', 'Updated At', NULL, 'datetime', NULL, false, false, true, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0003', 'Status', '工单当前状态', 'select', '{"options": [{"id": "todo", "name": "Todo", "color": "#e5e5e5"}, {"id": "in_progress", "name": "In Progress", "color": "#00b8d9"}, {"id": "at_repair_center", "name": "At Repair Center", "color": "#ff8b00"}, {"id": "awaiting_deployment", "name": "Awaiting Deployment", "color": "#6554c0"}, {"id": "scheduled_for_maintenance", "name": "Scheduled for Maintenance", "color": "#36b37e"}, {"id": "testing", "name": "Testing", "color": "#0052cc"}, {"id": "canceled", "name": "Cancel", "color": "#ff0000"}, {"id": "done", "name": "Done", "color": "#00875a"}]}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0010', 'Label', NULL, 'multi_select', '{"options": [{"id": "bug", "name": "Bug", "color": "#ff0000"}, {"id": "feature", "name": "Feature", "color": "#800080"}, {"id": "improvement", "name": "Improvement", "color": "#0000ff"}]}', false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0012', 'Asignee', NULL, 'user', NULL, false, false, false, NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, nullable, readonly, "createdAt", "updatedAt", "deletedAt") VALUES ('property0013', 'Reporter', NULL, 'user', NULL, false, false, false, NOW(), NOW(), NULL);
