import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { MdInbox, MdViewList, MdSettings } from "react-icons/md";
import { FaCode, FaServer } from "react-icons/fa";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 示例菜单项
const sidebarSections = [
  [
    { id: "inbox", label: "Inbox", icon: <MdInbox size={20} /> },
    { id: "views", label: "Views", icon: <MdViewList size={20} /> },
  ],
  [
    { id: "issues", label: "Issues", icon: <FaCode size={18} /> },
    { id: "miners", label: "Miners", icon: <FaServer size={18} /> },
  ],
  [
    { id: "settings", label: "Settings", icon: <MdSettings size={20} /> },
  ],
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar sections={sidebarSections} />
        <main className="ml-64">
          {children}
        </main>
      </body>
    </html>
  );
}
